version : '3'
services:
  backend :
    build:
      context: .
    command : sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: 'postgres:14'
    env_file:
      - '.env'
    environment:
      POSTGRES_DB : '${NAME}'
      POSTGRES_USER : '${USER}'
      POSTGRES_PASSWORD : '${PASSWORD}'
    volumes:
      - 'new-db:/var/lib/postgresql/data'
volumes:
  new-db:

