# Generated by Django 5.1.6 on 2025-03-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Укажите длительеость фильма'),
        ),
    ]
