# Generated by Django 5.1.6 on 2025-03-11 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_remove_movie_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='movies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='movie_app.movie'),
        ),
    ]
