# Generated by Django 5.1.6 on 2025-03-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_director_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
    ]
